### ISSUE TITLE
Remove useless commands

### ISSUE THREAD

**Issue by gabru-md** [gabru-md/contributors.md#2]
Remove useless commands from `contrib.py` file.

Commands like:
```python
#print type(args.repo)
```
which are commented must be removed.

Thanks!

**Comment by elina-codes** [comment]
I'd like to work on this issue! To be clear, you want just the commented lines removed?

**Comment by MJP85540** [comment]
It looks like this has already been taken care of but let me know if you could use any other help!

**Comment by shreyag12** [comment]
Hi, i did not find any useless commands in contrib.py file. Could you please elaborate what else needs to be removed?

**Comment by gabru-md** [comment]
Sorry @shreyag13 byt the issue has been resolved.
Thanks for showing interest though.
